#!/usr/bin/env python3
"""
Build a single-file preview.html.

index.html is the real site: it fetches /data/*.json and needs a web server.
preview.html is the same page with the CSS, JS, JSON and portrait inlined so
it opens by double-click, with no server. Content still has one source of
truth — this script reads it from /data. Re-run after editing any JSON.

    python3 tools/build_preview.py
"""

import base64
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_KEYS = ["profile", "experience", "projects", "skills", "navigation"]
CSS_FILES = ["assets/css/tokens.css", "assets/css/styles.css"]
JS_FILES = [
    "assets/js/theme.js",
    "assets/js/data.js",
    "assets/js/render.js",
    "assets/js/nav.js",
    "assets/js/main.js",
]
IMAGE = "assets/img/vishodhan-krishnan.jpg"


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def main() -> int:
    html = read("index.html")

    # --- content, read straight from /data so there is no second copy ---
    data = {}
    for key in DATA_KEYS:
        path = ROOT / "data" / f"{key}.json"
        try:
            data[key] = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"Invalid JSON in {path.name}: {exc}", file=sys.stderr)
            return 1

    # --- portrait as a data URI ---
    img_b64 = base64.b64encode((ROOT / IMAGE).read_bytes()).decode("ascii")
    data_uri = f"data:image/jpeg;base64,{img_b64}"
    data["profile"]["photo"]["src"] = data_uri

    # --- swap stylesheet links for inline styles ---
    for rel in CSS_FILES:
        html = html.replace(
            f'<link rel="stylesheet" href="{rel}">',
            f"<style>\n{read(rel)}\n</style>",
        )

    # --- swap script tags for inline scripts ---
    for rel in JS_FILES:
        html = html.replace(
            f'<script src="{rel}"></script>',
            f"<script>\n{read(rel)}\n</script>",
        )

    # Favicon and og:image stay as relative paths in index.html; inlining the
    # portrait three times tripled the preview for no benefit, so drop them.
    html = html.replace(f'  <link rel="icon" href="{IMAGE}">\n', "")
    html = html.replace(f'  <meta property="og:image" content="{IMAGE}">\n', "")

    # --- inject the content ahead of the loader ---
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    inline = (
        "<script>\n"
        "/* Generated by tools/build_preview.py — do not edit.\n"
        "   Source of truth is /data/*.json. Re-run the script after changes. */\n"
        f"window.__PORTFOLIO_DATA__ = {payload};\n"
        "</script>"
    )
    marker = "<script>\n" + read(JS_FILES[1])
    if marker not in html:
        print("Could not find the data loader to inject before.", file=sys.stderr)
        return 1
    html = html.replace(marker, inline + "\n" + marker, 1)

    # the load-error block can never fire in the inlined build
    html = re.sub(
        r'\s*<div class="pf-shell">\s*<div class="pf-notice" id="load-error" role="alert" hidden></div>\s*</div>',
        "",
        html,
    )

    out = ROOT / "preview.html"
    out.write_text(html, encoding="utf-8")
    size = out.stat().st_size / 1024
    print(f"Wrote {out.relative_to(ROOT)}  ({size:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
